### ISSUE TITLE
Verificar categoria pessoa antes deletar

### ISSUE THREAD

**Issue by joserogerio** [realsistemascaldas/sig#107]
Verificar se a categoria está relacionada com alguma pessoa antes de deletar a mesma

**Comment by renatoferreira1986** [comment]
Acabei de deletar o estado de goias kkkkkkk
[Uploading WhatsApp Image 2019-01-20 at 17.57.56.jpeg...]

**Comment by renatoferreira1986** [comment]
![WhatsApp Image 2019-01-20 at 17.57.56.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfb1cf15bc3d2000a54082/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762a6454f26622d5a329ab022a56415a49b2445e4d58eeb9cb74fce36f34985619e8836e0972903845abb98717b750ba208a1a84e7b48919c6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe94d54a0163662e3763e6e0a.jpeg)
