### ISSUE TITLE
Retirar cadastro permissões

### ISSUE THREAD

**Issue by joserogerio** [realsistemascaldas/sig#130]
Verificar possibilidade de não mostrar cadastro de permissões para o usuário do sistema.
Esse cadastro não tem utilidade para o usuário final.

**Comment by joserogerio** [comment]
Será retirado apenas o menu de cadastro de permissões, o cadastro de usuários e grupos ainda ficará no sistema.
Caso queira cadastrar uma permissão pode acessar diretamente através da url: 
sig.realsistemas.net/admin/permissao
Mas não tem muito sentido o usuário cadastrar uma permissão, seria mais restrito ao suporte mesmo.

**Comment by renatoferreira1986** [comment]
Ue no meu ta aparecendo o cadastro de permissoes

**Comment by joserogerio** [comment]
Ai que buro!
Você está testando as features 'Em progresso'?
