### ISSUE TITLE
Erro listagem de pagamentos

### ISSUE THREAD

**Issue by joserogerio** [realsistemascaldas/sig#73]
Não está mostrando o valor total dos juros ao ver os detalhes de uma conta

**Comment by joserogerio** [comment]
Está mostrando correntamente

**Comment by renatoferreira1986** [comment]
Especifique qual e a tela...

**Comment by joserogerio** [comment]
Os detalhes de uma conta só podem ser vistos ao editar uma conta (conta a pagar ou receber).
