### ISSUE TITLE
Baixa em contas, msg motivo do cancelamento

### ISSUE THREAD

**Issue by renatoferreira1986** [realsistemascaldas/sig#81]
Quando se da a baixa em uma conta, e posteriomente abrimos a mesma, nao aparece a msg do motivo do cancelamento da conta.

**Comment by joserogerio** [comment]
Baixa e cancelamento são conceitos diferentes.
Baixa é efetuada ao pagar uma conta já o cancelamento pode ser por um erro por exemplo.

**Comment by joserogerio** [comment]
O motivo do cancelamento de uma conta aparece nas observações ao clicar em editar e depois em Detalhes.
