### ISSUE TITLE
Contas a receber-Soma valor pago erro

### ISSUE THREAD

**Issue by renatoferreira1986** [realsistemascaldas/sig#82]
O valor pago esta sendo calculado errado

**Comment by renatoferreira1986** [comment]
![WhatsApp Image 2018-12-28 at 10.17.45 (1).jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfb1cf15bc3d2000a54082/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6455f16622dda329ab022a51415e49b2455d4f5cfde09b37b4f67e2fd00958a9c3674d71943e47aaee874bb800bf28831e85b6bddf4d91e03e70e199935d7c4f5b4cd6a2047ff5db59c24af74ceb4c50a0163f6aef70377d4392196761.jpeg)
![WhatsApp Image 2018-12-28 at 10.17.45 (2).jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfb1cf15bc3d2000a54082/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6455f16622dda329ab022a51415e49b2455d4f5cfee09b37b4f67e2fd00958a9c3674d71943e47aaee874bb800bf28831e85b6bddf4d91e03e70e199935d7c4f5b4cd6a2047ff5db59c24af74ceb4c50a0163f6aef70377d43941b6761.jpeg)
![WhatsApp Image 2018-12-28 at 10.17.45.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfb1cf15bc3d2000a54082/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6455f16622dda329ab022a51415e49b2455d4d58eeb9cb74fce36f34985619e8836e0972903845abb98717b750ba208a1a84e7b48919c6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe4445cad153762e57f3e6e0a.jpeg)

**Comment by joserogerio** [comment]
Contas antigas podem conter erros diversos, para verificar o sistema deve-se cadastrar contas novas e realizar os testes nelas.
