### ISSUE TITLE
Tela últimas mudanças

### ISSUE THREAD

**Issue by joserogerio** [realsistemascaldas/sig#84]
Criar tela que lista as últimas alterações no sistema

**Comment by joserogerio** [comment]
Foi criado um arquivo de mudanças (changelog) no github: 
https://github.com/realsistemascaldas/sig/blob/master/CHANGELOG.md
Arquivo referenciado no rodapé do sistema, acessado quando o usuário clicar na versão.

**Comment by renatoferreira1986** [comment]
Top heim
