### ISSUE TITLE
Receitas-Painel de controle

### ISSUE THREAD

**Issue by renatoferreira1986** [realsistemascaldas/sig#89]
Cadastrei uma conta para o mes subsequente, e dei baixa no mes corrente, o sistema nao contabilizou a conta paga no Painel de Receitas

**Comment by joserogerio** [comment]
Obs.: Refazer todo o sql que busca os dados, pois estava buscando as contas lançadas independentes de terem sido pagas. 
Buscar os dados das contas efetivamente pagas, assim como acontece no fluxo de caixa.
