### ISSUE TITLE
Apagar contas bancárias

### ISSUE THREAD

**Issue by joserogerio** [realsistemascaldas/sig#92]
Adicionar a possibilidade de apagar uma conta bancária.
Obs.: Deve existir pelo menos uma conta bancária cadastrada e não pode deletar conta bancária que já tenha conta a pagar ou receber lançada nela.

**Comment by renatoferreira1986** [comment]
Se for uma conta recorrente ele ainda apagara a conta bancaria ?

**Comment by realsistemascaldas** [comment]
Se a conta recorrente estiver vinculada a conta bancária, o sistema não permitirá deletar.
