### ISSUE TITLE
Permissões Cad. Bairros, Cidades e Estados

### ISSUE THREAD

**Issue by realsistemascaldas** [realsistemascaldas/sig#98]
Implementar uso de perrmissões nos cadastros:
*Bairros;
*Cidades;
*Estados

**Comment by joserogerio** [comment]
Dica para teste: Retirar as permissões de visualizar, cadastrar, atualizar e deletar dos cadastros de bairros, cidades e estados. Após isso tentar executar cada uma das funções que foi retirada, conceder novamente as permissões ao grupo do usuário e mais uma vez tentar executar as funções.
